#ifndef SC
#define SC
#include <Arduino.h>

const String notFound=
"<html>"
"  <head>"
"      <meta name=\"viewport\" content=\"width=device-width\">"
"    <title>🚆 REAW Train</title><meta charset=\"utf-8\"/>"
"    <style>"
"*{"
"    font-family: \"Verdana\";"
"}"
"body{"
"    color:#0c343d;"
"}"
".kontener {"
"    border-radius: 10px;"
"    border: 2px solid #345C65;"
"    padding: 3px;"
"    display:inline-block;"
"}"
".footer {"
"    position: fixed;"
"    left:5%;"
"    right:5%;"
"    bottom: 0;"
"    text-align: center;"
"    background-color:#FFFFFF;"
"    opacity:1;"
"}"
"   </style>"
"  </head>"
"  <body>"
"    <center>"
"        <h1>Mozdony vezérlő 📡</h1>"
"        <div class=\"kontener\"> "
"            <a href=\"/\">Tovább a főoldalra</a>"
"        </div>"
"        </center>"
"        <div class=\"footer kontener\">Powered by Turai Botond &copy;2021</div>"
"    </body>"
"</html>";

const String thx=
"<html>"
"  <head>"
"      <meta name=\"viewport\" content=\"width=device-width\">"
"    <title>🚆 REAW Train</title><meta charset=\"utf-8\"/>"
"    <style>"
"*{"
"    font-family: \"Verdana\";"
"}"
"body{"
"    color:#0c343d;"
"}"
".kontener {"
"    border-radius: 10px;"
"    border: 2px solid #345C65;"
"    padding: 3px;"
"    display:inline-block;"
"}"
".footer {"
"    position: fixed;"
"    left:5%;"
"    right:5%;"
"    bottom: 0;"
"    text-align: center;"
"    background-color:#FFFFFF;"
"    opacity:1;"
"}"
"   </style>"
"  </head>"
"  <body>"
"    <center>"
"        <h1>Mozdony vezérlő 📡</h1>"
"        <div class=\"kontener\"> "
"            Köszi, hogy kipróbáltad.<br>"
"            <a href=\"/\">Vissza a főoldalra</a>"
"        </div>"
"        </center>"
"        <div class=\"footer kontener\">Powered by Turai Botond &copy;2021</div>"
"    </body>"
"</html>";

const String easter=
"<html>"
"  <head>"
"      <meta name=\"viewport\" content=\"width=device-width\">"
"    <title>🚆 REAW Train</title><meta charset=\"utf-8\"/>"
"    <style>"
"*{"
"    font-family: \"Verdana\";"
"}"
"body{"
"    color:#0c343d;"
"}"
".kontener {"
"    border-radius: 10px;"
"    border: 2px solid #345C65;"
"    padding: 3px;"
"    display:inline-block;"
"}"
".footer {"
"    position: fixed;"
"    left:5%;"
"    right:5%;"
"    bottom: 0;"
"    text-align: center;"
"    background-color:#FFFFFF;"
"    opacity:1;"
"}"
"   </style>"
"  </head>"
"  <body>"
"    <center>"
"        <h1>Mozdony vezérlő 📡</h1>"
"        <div class=\"kontener\"> "
"            Gratulálok, megtaláltad az easter egg-et 😀<br>"
"            <a href=\"/\">Vissza a főoldalra</a>"
"        </div>"
"        </center>"
"        <div class=\"footer kontener\">Powered by Turai Botond &copy;2021</div>"
"    </body>"
"</html>";

const String controlPage=
"<html>"
"  <head>"
"      <meta name=\"viewport\" content=\"width=device-width\">"
"    <title>🚆 REAW Train</title><meta charset=\"utf-8\"/>"
"    <style>"
"*{"
"    font-family: \"Verdana\";"
"}"
"body{"
"    color:#0c343d;"
"}"
"input[type=range][orient=vertical]{"
"    writing-mode: bt-lr;"
"  -webkit-appearance: slider-vertical;"
"  width: 8px;"
"  height: 175px;"
"  padding: 0 5px;"
"}"
"table {"
"  border-collapse: collapse;"
"  margin:4px;"
"  border-color: #dedede;"
"  border: 1px solid #dedede;"
"}"
".switch {"
"    position: relative;"
"  display: inline-block;"
"  width: 60px;"
"  height: 34px;"
"}"
".switch input { "
"    opacity: 0;"
"    width: 0;"
"    height: 0;"
"}"
".slider {"
"    position: absolute;"
"  cursor: pointer;"
"  top: 0;"
"  left: 0;"
"  right: 0;"
"  bottom: 0;"
"  background-color: #ccc;"
"  -webkit-transition: .4s;"
"  transition: .4s;"
"}"
".slider:before {"
"    position: absolute;"
"  content: \"\";"
"  height: 26px;"
"  width: 26px;"
"  left: 4px;"
"  bottom: 4px;"
"  background-color: white;"
"  -webkit-transition: .4s;"
"  transition: .4s;"
"}"
"input:checked + .slider {"
"    background-color: #2196F3;"
"}"
"input:focus + .slider {"
"    box-shadow: 0 0 1px #2196F3;"
"}"
"input:checked + .slider:before {"
"  -webkit-transform: translateX(26px);"
"  -ms-transform: translateX(26px);"
"  transform: translateX(26px);"
"}"
".slider.round {"
"    border-radius: 34px;"
"}"
".slider.round:before {"
"    border-radius: 50%;"
"}"
".kontener {"
"    border-radius: 10px;"
"    border: 2px solid #345C65;"
"    padding: 3px;"
"    display:inline-block;"
"}"
".footer {"
"    position: fixed;"
"    left:5%;"
"    right:5%;"
"    bottom: 0;"
"    text-align: center;"
"    background-color:#FFFFFF;"
"    opacity:1;"
"}"
"    </style>"
"  </head>"
"  <body>"
"    <center>"
"        <h1>Mozdony vezérlő 📡</h1>"
"        <div class=\"kontener\"> "
"          <table border=\"1px\" height=\"400px\">"
"            <tr>"
"              <td colspan=\"2\" width=\"250px\">"
"                 <center><font style=\"vertical-align: middle;font-size:22px;font-weight: bold;\">Mozdony 🚂 </font></center><a href=\"logout\" title=\"Kilépés\" style=\"float:right;\" >Kilépés🚪</a>"
"              </td>"
"            </tr>"
"            <tr>"
"              <td width=\"50%\" height=\"38%\" style=\"vertical-align:top; text-align:center;\">"
"                  ⚙️ Motor <br><br>"
"                <label style=\"vertical-align:bottom;\" class=\"switch\">"
"                  <input type=\"checkbox\" id=\"engine1\" onchange='engine(\"engine1\");'>"
"                  <span class=\"slider round\"></span>"
"                </label>"
"              </td>"
"              <td  rowspan=\"2\" style=\"text-align:center; vertical-align:top;\">"
"                <h2>Sebesség</h2>"
"                <input id=\"speed1\" type=\"range\" orient=\"vertical\" value=\"0\" min=\"0\" max=\"255\" onchange='setSpeed(\"speed1\");'/>"
"              </td>"
"            </tr>"
"            <tr>"
"              <td height=\"38%\" style=\"vertical-align:top; text-align:center;\">"
"                  <font style=\"color:#1670BF\">➤</font>Menetirány<br>"
"                <button onclick='changeDir(\"left\")' title=\"Hátramenet\"><font id=\"left\" style=\"color:red; vertical-align:middle; font-size:50px;\">&#8592;</font></button>"
"                <button onclick='changeDir(\"right\")' title=\"Előremenet\"><font id=\"right\" style=\"color:green; vertical-align:middle; font-size:50px;\">&#8594;</font></button>"
"              </td>"
"            </tr>"
"            <tr>"
"              <td colspan=\"2\">"
"                <p id=\"debug\">&#8205;</p>"
"              </td>"
"            </tr>"
"          </table>"
"        </div>"
"            <br>"
"        </center>"
"        <div class=\"footer kontener\">Powered by Turai Botond &copy;2021</div>"
"    </body>"
"</html>"
"<script>"
"function setSpeed(id){"
"  var val=document.getElementById(id).value;"
"  if(val>=0 && val<=255){"
"      document.getElementById(\"debug\").innerHTML=\"Sebesség: \"+val;"
"      sendRequest(\"/set/?speed=\"+val);"
"  }"
"}"
"function changeDir(id){"
"  if(id==\"left\"){"
"    document.getElementById(\"left\").style.color=\"green\";"
"    document.getElementById(\"right\").style.color=\"red\";"
"    document.getElementById(\"debug\").innerHTML=\"Menetirány: hátramenet\";"
"    sendRequest(\"/set/?dir=for\");"
"  }else if(id==\"right\"){"
"    document.getElementById(\"left\").style.color=\"red\";"
"    document.getElementById(\"right\").style.color=\"green\";"
"    document.getElementById(\"debug\").innerHTML=\"Menetirány: előremenet\";"
"    sendRequest(\"/set/?dir=back\");"
"  }"
"  else{"
"    document.getElementById(\"debug\").innerHTML=\"Hibás menetirány paraméter\";"
"  }"
"}"
"function engine(id){"
"  var val=document.getElementById(id).checked;"
"  if(val){"
"    document.getElementById(\"debug\").innerHTML=\"Motor: bekapcsolva\";"
"    sendRequest(\"/set/?engine=on\");"
"  }else{"
"    sendRequest(\"/set/?engine=off\");"
"    document.getElementById(\"debug\").innerHTML=\"Motor: leállítva\";"
"  }"
"}"
"function sendRequest(req){"
"  var xhttp = new XMLHttpRequest();"
"  xhttp.open(\"GET\",req, true);"
"  xhttp.send();"
"  xhttp.onreadystatechange = function() {"
"    if (this.readyState != 4 && this.status!=200)"
"        location.replace(\"/?timeout=true\");"
"  };"
"}"
"</script>";

const String waiting=
"<html>"
"  <head>"
"      <meta name=\"viewport\" content=\"width=device-width\">"
"    <title>🚆 REAW Train</title><meta charset=\"utf-8\"/>"
"    <style>"
"*{"
"    font-family: \"Verdana\";"
"}"
"body{"
"    color:#0c343d;"
"}"
".kontener {"
"    border-radius: 10px;"
"    border: 2px solid #345C65;"
"    padding: 3px;"
"    display:inline-block;"
"}"
".footer {"
"    position: fixed;"
"    left:5%;"
"    right:5%;"
"    bottom: 0;"
"    text-align: center;"
"    background-color:#FFFFFF;"
"    opacity:1;"
"}"
"   </style>"
"  </head>"
"  <body>"
"    <center>"
"        <h1>Mozdony vezérlő 📡</h1>"
"        <div class=\"kontener\"> "
"            Hamarosan te is sorra kerülsz."
"        </div>"
"        </center>"
"        <div class=\"footer kontener\">Powered by Turai Botond &copy;2021</div>"
"    </body>"
"</html>";

const String timeOut=
"<html>"
"  <head>"
"      <meta name=\"viewport\" content=\"width=device-width\">"
"    <title>🚆 REAW Train</title><meta charset=\"utf-8\"/>"
"    <style>"
"*{"
"    font-family: \"Verdana\";"
"}"
"body{"
"    color:#0c343d;"
"}"
".kontener {"
"    border-radius: 10px;"
"    border: 2px solid #345C65;"
"    padding: 3px;"
"    display:inline-block;"
"}"
".footer {"
"    position: fixed;"
"    left:5%;"
"    right:5%;"
"    bottom: 0;"
"    text-align: center;"
"    background-color:#FFFFFF;"
"    opacity:1;"
"}"
"   </style>"
"  </head>"
"  <body>"
"    <center>"
"        <h1>Mozdony vezérlő 📡</h1>"
"        <div class=\"kontener\"> "
"            Lejárt az időd.<br>"
"            Hamarosan ismét sorra kerülsz."
"        </div>"
"        </center>"
"        <div class=\"footer kontener\">Powered by Turai Botond &copy;2021</div>"
"    </body>"
"</html>";
#endif
